
name: My First Workflow

on:
  push:
    branches: [main]

jobs:
  data-quality:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install depedencies
        run: pip install -r requirements.txt
      - name: Lint code with flake8
        run: flake8 pipeline.py --max-line-length=100
      - name: Run data quality checks
        run: python3 pipeline.py